backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "index.html"
        label: "Homepage Content"
        name: "homepage"
        fields:
          - { label: "Welcome Heading", name: "welcome_heading", widget: "string" }
          - { label: "Welcome Message", name: "welcome_message", widget: "text" }
          - { label: "Update Box", name: "update_box", widget: "text" }
